language: ruby
rvm:
  - "1.25.33"
  - ruby-head
env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=master"
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
