# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7842779b1f180120c97a5e34979d4c89f4b801455778848a1720f969d5291da22fa58223d29e4c9b711d06d1f7c7f86faa59502bdab53b431ebc6fa94984c9d4

test:
  secret_key_base: 6f4aa930c848f8b6e06f82271369fabb8bd9e34ad5d0b8a7b34f18ffb077320797da448cb3168fe215539b36c511441fb9a4a81bfc8ae2d491586f77f6ff3f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
